### ISSUE TITLE
このorganizationの使い方が分からない場合の対処法

### ISSUE THREAD

**Issue by SugiyamaHaruka** [noguchi-lab-ibaraki/lab-github-policies#1]
このorganizationの使い方が分からない場合、誰にどのように聞けばいいですか？

**Comment by kumo-rn5s** [comment]
Ownerに聞いてください。

質問する場所は以下となります。
1. リポジトリlab-github-policiesのissues
2. Teamsの雑談チャンネル

issueの書き方について、lab-github-policiesのwiki画面で見れます。

[Issueの書き方](https://github.com/noguchi-lab-ibaraki/lab-github-policies/wiki/Issue%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9)

**Comment by SugiyamaHaruka** [comment]
Ownerが全員卒業している場合にはどうすればいいですか？

**Comment by kumo-rn5s** [comment]
教授または活躍中のOwnerに聞いてください
Owner卒業後、他のメンバーになりますので、教授経由で卒業生を聞いてください。

Ownerの権限について、以下のコミットで説明しています。
49687eb3ac65b1066062d598c0c85086941204ad
