### ISSUE TITLE
Githubを利用してこのように管理するメリットなどが知りたい

### ISSUE THREAD

**Issue by SugiyamaHaruka** [noguchi-lab-ibaraki/lab-github-policies#3]
なぜGithubを利用して、卒業研究をこのように管理するのかを知りたいです

**Comment by kumo-rn5s** [comment]
1. コードベースの共同作業
2. 共同作業ではない場合、IssuesとPullRequestとProject単位で、独自で課題管理することもできること
3. マイルストーン・labelなど、課題整理することが便利
4. githubを慣れることが就職活動中色々メリットがある
