### ISSUE TITLE
卒業研究テーマのリポジトリでは、何を管理すればいいのか

### ISSUE THREAD

**Issue by SugiyamaHaruka** [noguchi-lab-ibaraki/lab-github-policies#5]
卒業研究のテーマが決まり、リポジトリの作成などを行う場合に、
そのリポジトリでは何を管理すればいいのでしょうか？
発表資料（PPＴ）や、参考文献（pdfなど）を管理すればいいのでしょうか？

**Comment by kumo-rn5s** [comment]
Wikiで回答する
