### ISSUE TITLE
作成したリポジトリを教授以外の他人に見られたくない場合の対処法

### ISSUE THREAD

**Issue by SugiyamaHaruka** [noguchi-lab-ibaraki/lab-github-policies#6]
卒業研究が完成するまでは、教授以外の人に見せたくない資料があります。
どうすれば、教授だけには見えるけれど、それ以外の人には見られないように設定できますか？

**Comment by kumo-rn5s** [comment]
> 共同作業必要の Repository は 共同作業者だけをInviteする。ただし、Ownerはどの Repository にもフルアクセスを所持している

Github組織の管理上、教授だけがOwnerである場合、教授以外の他人が見れなくなります。
現時点では学生Ownerを設置し、管理を協力する目的なので、教授だけに見せたいリポジトリがあれば、組織外で作るしかないと思います。
