### ISSUE TITLE
先輩の卒業研究を受け継ぎたい場合にはどうするべきか

### ISSUE THREAD

**Issue by SugiyamaHaruka** [noguchi-lab-ibaraki/lab-github-policies#7]
卒業された先輩方の研究内容に似たものの研究を行いたいのですが、どうすれば先輩の研究内容を入手できますか？
また、そういった場合の注意点なども教えてほしいです

**Comment by kumo-rn5s** [comment]
Project -> 野口研究室研究テーマ　-> todo 
のところで卒業生が置いた研究があるので、そこから着手してください。

また、後任者に任せたい研究があれば、リポジトリを`noguchi-lab-all`チームにmaintainer権限を与え、野口研究室研究テーマのプロジェクトLinked-Repositoryにリポジトリ追加してください。todoのエリアで任せたいissueやpull requestを追加してください。
